spring:
  info:
    app:
      name: PersistenciaPoliglota
      description: Aplicación Spring Boot con persistencia poliglota (PostgreSQL, MongoDB, Redis)
      version: 0.0.1-SNAPSHOT
      encoding: UTF-8
      java:
        version: ${java.version}
    build:
      artifact: ${project.artifactId}
      group: ${project.groupId}
      name: ${project.name}
      version: ${project.version}
    git:
      branch: ${git.branch:unknown}
      commit:
        id: ${git.commit.id:unknown}
        time: ${git.commit.time:unknown}
